### ISSUE TITLE
Type error when setting date and/or time

### ISSUE THREAD

**Issue by monojk** [KitronikLtd/micropython-microbit-kitronik-rtc#1]
When trying to set date and time with:

```
rtc = KitronikRTC
rtc.setTime(rtc, 14, 0, 0)
rtc.setDate(rtc, 26, 7, 19)

while True:
    display.scroll(rtc.readTimeAndDate(rtc))
```
>>> Traceback (most recent call last):
  File "__main__", line 178, in <module>
  File "__main__", line 105, in setTime
  File "__main__", line 58, in decToBcd
TypeError: unsupported types for : 'float', 'int'

Changing line 58 to the following helps:
`        tens = int(decNumber / 10)
`

**Comment by Lorrainbow** [comment]
This is still an issue. 

tens = decNumber // 10 

would also fix it.

**Comment by PhilAtKitronik** [comment]
The issue has been changed with the latest git commit.  Code has been tested.  Please see if everything is working for your application.

**Comment by Lorrainbow** [comment]
Fixed, thank you.
