### ISSUE TITLE
Incorrect masks

### ISSUE THREAD

**Issue by Lorrainbow** [KitronikLtd/micropython-microbit-kitronik-rtc#2]
Hello,

Looking up the chip datasheet for this, the masks are incorrect.

This was what I came up with: 
        if readReg == self.RTC_SECONDS_REG:
            mask = 0x70
        elif readReg is self.RTC_MINUTES_REG:
            mask = 0x70
        elif readReg is self.RTC_DAY_REG:
            mask = 0x30
        elif readReg is self.RTC_HOURS_REG:
            mask = 0x30
        elif readReg is self.RTC_MONTH_REG:
            mask = 0x10
        elif readReg is self.RTC_YEAR_REG:
            mask = 0xF0

**Comment by Lorrainbow** [comment]
When rtc.readTimeAndDate(rtc) is called seconds always = minutes.. (but they are counting upwards) 
I don't know if that's a mask problem which is why this is an issue rather than a pull request

**Comment by PhilAtKitronik** [comment]
The issue has been changed with the latest git commit.  Code has been tested.  Please see if everything is working for your application.

**Comment by Lorrainbow** [comment]
Hi,
If you set the time with minutes and seconds being different, like so:

`rtc = KitronikRTC
rtc.setTime(rtc,14,4,20)
rtc.setDate(rtc, 12,3,21)
while True:
    display.scroll(rtc.readTimeAndDate(rtc))`

It displays 14:4:4 as the time. And it starts counting seconds from 4, not 20.

**Comment by PhilAtKitronik** [comment]
Push fix, Set Date was affecting the seconds register.  Code has been tested.  Code has been improved to save space and time will always show two digits for hours, minutes and seconds
