### ISSUE TITLE
More detailed datasheet needed

### ISSUE THREAD

**Issue by Lorrainbow** [KitronikLtd/micropython-microbit-kitronik-rtc#3]
I'm trying to add external buttons to the pad on the back but none of them are working, particularly in micropython. An idea of what pins are being used by this board would be very helpful. 

Soldering issues aside.

The micropython code below always produces buttonState 1, regardless of what the button does. 
While in MakeCode the block "on pin P1 pressed" works. :|  

The line 
```
buttonState = pin2.read_digital()   #always produces 1
buttonState = pin2.is_touched()  #was also used and always produces 0

```
Both scenarios were tested on a V1, V2 and the button connected to GND and 3V as well as pin2. 

```
while True:           
    buttonState = pin2.read_digital()   
    
    if buttonState==1:
        display.show(Image.HAPPY)
        sleep(1000)
    else:
        display.show(Image.NO)
        sleep(1000)
    sleep(20)
```

**Comment by Lorrainbow** [comment]
You can ignore micropython and makecode acting differently! Found a bug on my side. 
Datasheet would still be nice :)

**Comment by PhilAtKitronik** [comment]
There is a datasheet for the device on the product webpage,  the datasheet is in the description section towards the bottom. I have updated the datasheet with an additional description with the micropython example (this version should be uploaded soon).
For the current version the link is here 
https://resources.kitronik.co.uk/pdf/5635-kitronik-realtime-clock-microbit-rtc-datasheet.pdf
